version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/myapp
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - php
    restart: always

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./public:/var/www/myapp
    restart: always

  composer:
    image: composer:latest
    command: [ "composer", "install" ]
    volumes:
      - ./public:/app
